spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/invoice_billingtracker_saas_db
spring.datasource.username=hoan
spring.datasource.password=15325

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





